name: "Echo value"
inputs:
  COOL_BOOLEAN:
    description: "Boolean value to echo"
    type: boolean
    default: false
runs:
  using: "composite"
  steps:
    - name: ⚙️ Echo
      shell: bash
      run: |
        echo "COOL_BOOLEAN: ${{ inputs.COOL_BOOLEAN }}"
        echo "EQ_TRUE: ${{ inputs.COOL_BOOLEAN == true }}"
        echo "EQ_FALSE: ${{ inputs.COOL_BOOLEAN == false }}"
        echo "EQ_STR_TRUE: ${{ inputs.COOL_BOOLEAN == 'true' }}"
        echo "EQ_STR_FALSE: ${{ inputs.COOL_BOOLEAN == 'false' }}"
    - name: 📦 Execute if true
      if: ${{ inputs.COOL_BOOLEAN == 'true' }}
      shell: bash
      run: |
        echo "COOL_BOOLEAN is true"
    - name: 📦 Execute if false
      if: ${{ inputs.COOL_BOOLEAN == 'false' }}
      shell: bash
      run: |
        echo "COOL_BOOLEAN is false"