name: Job Share

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Get server port
        id: get_server_port
        run: |
          echo "SERVER_PORT=8000"  >> $GITHUB_OUTPUT

  job2:
    needs: [job1]
    name: Job 2
    runs-on: ubuntu-latest
    steps:
      - name: Log server port
        run: |
          echo "${{fromJson(needs.job1.outputs)}}"
          echo "$SERVER_PORT"
