name: Manual Job Trigger

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 1
        run: echo "Auto Job 1"

  job2:
    if: false
    needs: [job1]
    name: Job 2
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 2
        run: echo "Manually triggered"
