name: Create release tag with push

on:
  push:
    tags:
      - 'common-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
    create-tag:
        if: github.event.created
        runs-on: ubuntu-latest
        steps:
            - run:  echo ${{github.ref_name}}
